stages:
- build
- deploy

build:
  stage: build
  tags:
  - kfcoding
  script:
  - docker build -t $IMAGE .
  - docker push $IMAGE

deploy:
  stage: deploy
  tags:
  - kfcoding
  script:
  - curl $UPDATE_HOOK
