language: bash

dist: xenial

services:
  - docker

script:
  - echo "test"
  - echo $TRAVIS_TAG

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    condition: '$TRAVIS_TAG =~ ^release-[0-9.]+$'
