language: bash

dist: xenial

services:
  - docker

script:
  - echo "testing"
  - echo $TRAVIS_BRANCH

notifications:
  slack: gitcourse:$SLACK_NOTIFICATION_KEY

deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release-[0-9.]+$

notifications:
  slack: gitcourse:$SLACK_NOTIFICATION_KEY